### ISSUE TITLE
Triggering command when the page already exists

### ISSUE THREAD

**Issue by pringshia** [frankolson/obsidian-tomorrows-daily-note#5] opened 2022-01-27 00:59 UTC
It might be nice to just jump to the new page instead of throwing the "Unable to create new file." error if the command is triggered again.

My workflow is to just jump to tomorrow's page (and create if it doesn't exist) using the command this plugin provides via a hotkey.

EDIT: Looking at the [source code](https://github.com/frankolson/obsidian-tomorrows-daily-note/blob/19e2dc08e766a9559e30a133a9b2f8e0c0a4ec66/src/OpenTomorrowsDailyNote.ts#L34-L39) it does seem like that it should go to the page if it already exists, however I get this:

<img width="239" alt="Screen Shot 2022-01-26 at 8 36 44 PM" src="https://user-images.githubusercontent.com/425059/151275725-017ded2b-0abd-498b-b18d-8fc417168f66.png">

**Comment by frankolson** [comment] 2024-04-21 16:05
Hey @pringshia, I cannot seem to recreate this. Could you try reproducing this with new vault and add steps to reproduce?

**Comment by frankolson** [comment] 2024-10-04 23:43
Closing due to the age and because the issue cannot be reproduced. Will reopen if more context is added to help with steps to reproduce.

**Closed as completed by frankolson** 2024-10-04 23:43 UTC
